version: '3.9'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/client
    depends_on:
      - server
  server:
    build: ./server
    env_file:
      - .env
    ports:
      - "4000:3000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
    volumes:
      - /app/node_modules
      - ./server:/server
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
