version: '3.1'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/client
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "4000:3000"
    volumes:
      - /app/node_modules
      - ./server:/server
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      -POSTGRES_PASSWORD: mypassword
      -POSTGRES_USER: myusername
      -POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
